<?php
/**
 * Created by PhpStorm.
 * User: cSteusloff
 * Date: 12.12.13
 * Time: 14:58
 */

?>
<script src="js/codemirror.js"></script>
<link rel="stylesheet" href="css/codemirror.css">
<script src="js/sql.js"></script>
<script>
    window.onload = function() {
        window.editor = CodeMirror.fromTextArea(document.getElementById('code'), {
            mode: 'text/x-mysql',
            indentWithTabs: true,
            smartIndent: true,
            lineNumbers: true,
            matchBrackets : true,
            autofocus: false
        });
    };
</script>


Tabellen werden über SQL-Developer angelegt mit dem präfix "master_"<br>
Auswahl der Tabellen für diese Aufgabe<br>
Überschrift<br>
Text<br>
Berechtigungen setzen (Select, Update/Insert)<br>
Muster-Query<br>

<? require_once 'site/form/formCreateTask.php'; ?>
