<?php
/**
 * Project: Softwareprojekt
 * User: Christian Steusloff
 * Date: 13.12.13
 * Time: 11:40
 */
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<script src="js/codemirror.js"></script>
<link rel="stylesheet" href="css/codemirror.css">
<script src="js/sql.js"></script>
<script>
    window.onload = function() {
        window.editor = CodeMirror.fromTextArea(document.getElementById('code'), {
            mode: 'text/x-mysql',
            indentWithTabs: true,
            smartIndent: true,
            lineNumbers: true,
            matchBrackets : true,
            autofocus: false
        });
    };
</script>
<style type="text/css">

    div.task span{
        font-weight: bold;
        margin-left: 3px;
    }

    div.task table{
        border-collapse:collapse;
        border:1px solid green;
        margin: 3px;
    }

    div.task table th{
        background-color:green;
        color:white;
        border: 1px solid black;
    }

    div.task table td {
        border: 1px solid black;
    }

    div.task table tr:nth-child(odd) {
        background-color: cornsilk;
    }
    div.task table tr:nth-child(even) {
        background-color: aquamarine;
    }

    #container{
        width: 100%;
        border: solid black 2px;
    }
</style>
<script src="js/masonry.pkgd.min.js"></script>
<?php
require_once 'library/oracleConnection.class.php';
require_once 'library/sqlFormatter.class.php';
require_once 'library/taskHandler.php';
require_once 'library/taskHelper.php';
require_once 'library/queryTranslator.class.php';

require_once 'library/sqlValidator.class.php';
//use library\sqlValidator;



$tH = new taskHandler();#

var_dump($_POST);

?>

<form action="" method="post">
    <select name="task">
        <?php
        foreach($tH->getSelect() as $key => $task){
            if($_POST['task'] == $key){
                echo("<option value='{$key}' selected='selected'>{$task}</option>");
            } else {
                echo("<option value='{$key}'>{$task}</option>");
            }
        }
        ?>
    </select>
    <input type="submit" name="choice" value="anzeigen">
</form>

<?php

if(isset($_POST["choice"])){

    $task = new taskHelper($_POST['task']);
    echo("<h2>Lösungs-Query</h2>");
    echo(SqlFormatter::format($task->getSolution()));
?>
<div id="container" class="js-masonry" data-masonry-options='{ "columnWidth": 2, "itemSelector": ".task" }'>
    <?php echo($task->printTable("task"));?>
</div>
<form action="" method="post">
        <input type="hidden" name="task" value="<?php echo($_POST['task']);?>">
        <textarea id="code" name="code" rows="5"><?php echo isset($_POST["code"]) ? $_POST["code"] : "SELECT
          c.cname as Cocktail,
          z.zname as Zutat,
          zc.menge as Menge
        FROM
          (SELECT cid,cname FROM Cocktail WHERE alkoholisch != 'n') c
        INNER JOIN Zutat_Cocktail zc ON c.cid = zc.cid
        INNER JOIN Zutat z ON zc.zid = z.zid"?></textarea>
        <input type="submit" name="choice" value="testen">
</form>
<?php
}
    if(!empty($_POST["code"])){
        require_once 'library/validate.inc.php';
        //require_once 'library/queryTranslator.class.php';

        $qT = new queryTranslator();
        $query = $qT->translate($_POST["code"],"MASTER_");
        echo(SqlFormatter::format($query));

        // Syntax-Check!
        echo("<h2>Master Lösung</h2>");
        $db = new oracleConnection();
        $task = new taskHelper($_POST['task']);
        $db->Query($task->getSolution());
        echo $db->printTable("task");

        echo("<h2>studentische Lösung</h2>");
        $db->Query($query);
        echo $db->printTable("task");

        $validator = new \lib\sqlValidator\sqlValidator($db);
        $validator->validate($task->getSolution(),$query);


        echo("<h1>");
        @validate($task->getSolution(),$query);
        echo("</h1>");
    }

//
//
//
//}
//
//
//
//// TEST-UMGEBUNG
//
//$db = new oracleConnection();
//$prefix = "MASTER_";
//$db->Query("SELECT TABLE_NAME FROM ALL_TABLES
//            WHERE UPPER(TABLE_NAME) LIKE '{$prefix}%COCKTAIL'
//            OR UPPER(TABLE_NAME) LIKE '{$prefix}%ZUTAT%'");
//
//$tables = array();
//
//while($db->Fetch(false)){
//$tables[] =$db->row[0];
//}
//
//var_dump($tables);
//
//$solution = "SELECT c.cname as Cocktail,
//                    z.zname as Zutat,
//                    zc.menge as Menge
//             FROM MASTER_Cocktail c, MASTER_Zutat z, MASTER_Zutat_Cocktail zc
//             WHERE c.cid = zc.cid
//             AND zc.zid = z.zid
//             AND alkoholisch LIKE 'y'";
//
//echo("<p>Lösung:<br>");
//echo(SqlFormatter::format($solution));
//echo("<p>");
//?>
<!---->
<!--<div id="container" class="js-masonry"-->
<!--     data-masonry-options='{ "columnWidth": 2, "itemSelector": ".task" }'>-->
<!--    --><?php
//
//    foreach($tables as $table){
//        $db->Query("SELECT * FROM {$table}");
//        echo($db->printTable("task",substr(strtoupper($table),strlen($prefix))));
//    }
//    ?>
<!--</div>-->
<!---->
<!---->
<!--<form action="" method="post">-->
<!--    <textarea id="code" name="code" rows="5">--><?php //echo isset($_POST["code"]) ? $_POST["code"] : "SELECT
//  c.cname as Cocktail,
//  z.zname as Zutat,
//  zc.menge as Menge
//FROM
//  (SELECT cid,cname FROM MASTER_Cocktail WHERE alkoholisch != 'n') c
//INNER JOIN MASTER_Zutat_Cocktail zc ON c.cid = zc.cid
//INNER JOIN MASTER_Zutat z ON zc.zid = z.zid"?><!--</textarea>-->
<!--    <input type="submit" value="testen">-->
<!--</form>-->

<?php





// SQL-Primary Key auslesen:

//SELECT cols.table_name, cols.column_name, cols.position, cons.status, cons.owner
//FROM all_constraints cons, all_cons_columns cols
//WHERE cols.table_name = 'MASTER_COCKTAIL'
//AND cons.constraint_type = 'P'
//AND cons.constraint_name = cols.constraint_name
//AND cons.owner = cols.owner
//ORDER BY cols.table_name, cols.position;




?>